### ISSUE TITLE
Error: Error adding entities for domain sensor with platform google_fit / Error while setting up google_fit platform for sensor

### ISSUE THREAD

**Issue by Stele77** [cyberjunky/home-assistant-google_fit#11]
Hi!
I tried to setup this integration, but it produces an error on startup and does not create the entities with my Google Fit data:

`Logger: homeassistant.components.sensor
Source: custom_components/google_fit/sensor.py:247
Integration: Sensor (documentation, issues)
First occurred: 13:35:23 (2 occurrences)
Last logged: 13:35:23

Error adding entities for domain sensor with platform google_fit
Error while setting up google_fit platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 460, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/google_fit/sensor.py", line 247, in device_state_attributes
    return self._attributes
AttributeError: 'GoogleFitWeightSensor' object has no attribute '_attributes'`

Thanks for any help in advance!

**Comment by cyberjunky** [comment]
Will have a look

**Comment by Bubi504** [comment]
The same here.

**Comment by cyberjunky** [comment]
Stale issue, please update to latest version and (re)open ticket if needed.

**Comment by ndanzi** [comment]
Still got the same error, latest version of google_fit and home assistant

**Comment by Fvdzandt** [comment]
I have the same

**Comment by fabse-hacks** [comment]
yes, the same here!
