### ISSUE TITLE
Authentication code expired, please restart Home-Assistant and try again

### ISSUE THREAD

**Issue by LuckyTriple7** [cyberjunky/home-assistant-google_fit#12]
HASS 2021.07.04

I got permanent the following Error:

Authentication code expired, please restart Home-Assistant and try again

```
2021-07-23 11:31:04 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform google_fit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 460, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/google_fit/sensor.py", line 247, in device_state_attributes
    return self._attributes
AttributeError: 'GoogleFitWeightSensor' object has no attribute '_attributes'

```
Client ID and Client Secret is correct and working with the Google Calendar Integration.
Google Fitness API is also enabled.

**Comment by JonathanTreffler** [comment]
I have the same issue !

**Comment by boyphongsakorn** [comment]
I have the same issue !

**Comment by tripplehelix** [comment]
Me too, is this an issue on the integrations side?

**Comment by sethakeawmok** [comment]
I have the same issue ! and i cut 
SCOPES = ['https://www.googleapis.com/auth/fitness.body.read',
    'https://www.googleapis.com/auth/fitness.body.write',
    'https://www.googleapis.com/auth/fitness.activity.read',
    'https://www.googleapis.com/auth/fitness.location.read']
    
    after it work but not show heartrate and token use 1 hour not update

**Comment by Backslashh** [comment]
Same issue here.

**Comment by Backslashh** [comment]
Set your HA timezone to `Etc/UTC` then restart HA. You'll get a notification to Authenticate. Once the Auth with Google is complete, you can change your timezone back and restart.

**Comment by Mio3000** [comment]
The sensors working on GMT , but when i change the tíme zone back, they stop to update itself… any workarounds pls?

**Comment by cyberjunky** [comment]
Stale issue, closing, please update to latest version and (re)open ticket if needed.
