### ISSUE TITLE
googleapiclient.errors.UnknownApiNameOrVersion: name: fitness  version: v1

### ISSUE THREAD

**Issue by syphernl** [cyberjunky/home-assistant-google_fit#21]
It seems that this integration is no longer working with HASS 2022.4:

```py
Traceback (most recent call last):
  File "/srv/hass/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/.homeassistant/custom_components/google_fit/sensor.py", line 180, in setup_platform
    client = _get_client(token_file)
  File "/home/hass/.homeassistant/custom_components/google_fit/sensor.py", line 103, in _get_client
    service = google_discovery.build(
  File "/srv/hass/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
  File "/srv/hass/lib/python3.9/site-packages/googleapiclient/discovery.py", line 287, in build
    service = json.loads(content)
  File "/srv/hass/lib/python3.9/site-packages/googleapiclient/discovery.py", line 404, in _retrieve_discovery_doc
    if schema_type == 'string':
googleapiclient.errors.UnknownApiNameOrVersion: name: fitness  version: v1
```

**Comment by janfajessen** [comment]
Same for me, Google Fit don't work in last 2022.4 version

**Comment by syphernl** [comment]
It's a bit weird because according to the docs v1 is the only API for Google Fit 🤔 

https://developers.google.com/fit/rest/v1/get-started

**Comment by syphernl** [comment]
And all of a sudden (or perhaps after 2022.4.3 the sensors are working again!
