### ISSUE TITLE
Authentication code expired, please restart Home-Assistant and try again

### ISSUE THREAD

**Issue by chatainsim** [cyberjunky/home-assistant-google_fit#25]
Hello,
I've update the component to the lastert version 1.0.6 but the issue still persist.
```
Logger: homeassistant.components.sensor
Source: custom_components/google_fit/sensor.py:282
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:51:55 (4 occurrences)
Last logged: 12:51:56
google_fit: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/google_fit/sensor.py", line 488, in update
    for point in self._get_dataset(self.DATA_SOURCE)["point"]:
  File "/config/custom_components/google_fit/sensor.py", line 282, in _get_dataset
    return self._client.users().dataSources(). \
AttributeError: 'NoneType' object has no attribute 'users'
```
```
Logger: homeassistant.components.sensor
Source: custom_components/google_fit/sensor.py:247
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:51:54 (2 occurrences)
Last logged: 12:51:55

    Error adding entities for domain sensor with platform google_fit
    Error while setting up google_fit platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/google_fit/sensor.py", line 247, in extra_state_attributes
    return self._attributes
AttributeError: 'GoogleFitWeightSensor' object has no attribute '_attributes'
```
I'm not able to authenticate.

**Comment by cyberjunky** [comment]
This error has nothing to do with not being able to authenticate.
You enabled Google Fit, and got client id and secret from Google console?
Filled them in into HA config entry?

Did you get a notifictation that HA needs to be linked to Google Fit?
Tried to switch timezone to Etc/UTC, see FAQ on readme.

Just posting this error and simply saying it doesn't work is not enough to help you, so please do above steps and report back for each...

**Comment by chatainsim** [comment]
Sorry, I was too quick. It's the same king of issue #12 
Configuration with client id and secret is done but unable to link my account.
All I have is Authentication code expired, please restart Home-Assistant and try again.
Regarding the timezone, all I have is GMT something, I don't have ETC/UTC.

**Comment by grastraa** [comment]
UTC is GMT+00:00
Worked for me by setting it to` (GMT+00:00) GMT (no daylight saving)`

**Comment by chatainsim** [comment]
Thanks @grastraa it's working now.
