### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by jellewie** [cyberjunky/home-assistant-google_fit#37]
I tried removing it, and following the steps again. But still the same results
I tried setting my time to "(GMT+00:00) GMT (no daylight saving)" but that also doesn't work
I checked the account, and I can see data in my Google fit myself though the app with the same account.
![image](https://user-images.githubusercontent.com/1545223/234492802-de4af6b6-efda-41bb-980a-2147db8ca4cc.png)

debug logs:
```
2023-04-26 08:51:22.643 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration google_fit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
...
2023-04-26 08:51:34.670 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.google_fit
...
2023-04-26 08:51:37.477 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform google_fit
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 635, in _async_write_ha_state
attr.update(self.extra_state_attributes or {})
File "/config/custom_components/google_fit/sensor.py", line 249, in extra_state_attributes
return self._attributes
AttributeError: 'GoogleFitWeightSensor' object has no attribute '_attributes'
2023-04-26 08:51:37.543 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/google_fit/sensor.py", line 430, in update
heartrate_datasources = self._get_datasources('com.google.heart_rate.bpm')
File "/config/custom_components/google_fit/sensor.py", line 274, in _get_datasources
datasources_request = self._client.users().dataSources().list(
AttributeError: 'NoneType' object has no attribute 'users'
2023-04-26 08:51:37.550 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 2.8 seconds
2023-04-26 08:51:37.555 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 2.7 seconds
2023-04-26 08:51:37.559 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 1.2 seconds
2023-04-26 08:51:37.568 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 1.8 seconds
2023-04-26 08:51:37.579 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up google_fit platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 635, in _async_write_ha_state
attr.update(self.extra_state_attributes or {})
File "/config/custom_components/google_fit/sensor.py", line 249, in extra_state_attributes
return self._attributes
AttributeError: 'GoogleFitWeightSensor' object has no attribute '_attributes'
2023-04-26 08:51:37.585 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 2.8 seconds
2023-04-26 08:51:37.749 INFO (MainThread) [homeassistant.setup] Setting up hacs
2023-04-26 08:51:37.750 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 0.0 seconds
2023-04-26 08:51:38.066 INFO (MainThread) [homeassistant.setup] Setting up goodwe
2023-04-26 08:51:38.067 INFO (MainThread) [homeassistant.setup] Setup of domain goodwe took 0.0 seconds
2023-04-26 08:51:38.095 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/google_fit/sensor.py", line 369, in update
height_datasources = self._get_datasources('com.google.height')
File "/config/custom_components/google_fit/sensor.py", line 274, in _get_datasources
datasources_request = self._client.users().dataSources().list(
AttributeError: 'NoneType' object has no attribute 'users'
2023-04-26 08:51:38.100 INFO (MainThread) [custom_components.hacs]
...
2023-04-26 08:51:38.151 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
...
File "/config/custom_components/google_fit/sensor.py", line 490, in update
for point in self._get_dataset(self.DATA_SOURCE)["point"]:
File "/config/custom_components/google_fit/sensor.py", line 284, in _get_dataset
return self._client.users().dataSources(). \
AttributeError: 'NoneType' object has no attribute 'users'
2023-04-26 08:51:38.163 DEBUG (SyncWorker_5) [custom_components.google_fit.sensor] Starttime 2023-04-25T17:00:00Z, Endtime 2023-04-26T11:00:00Z
2023-04-26 08:51:38.164 INFO (MainThread) [homeassistant.setup] Setting up stream
2023-04-26 08:51:38.309 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.1 seconds
2023-04-26 08:51:38.312 INFO (MainThread) [homeassistant.setup] Setting up button
2023-04-26 08:51:38.315 INFO (MainThread) [homeassistant.setup] Setup of domain button took 0.0 seconds
2023-04-26 08:51:38.321 INFO (MainThread) [homeassistant.setup] Setting up presence_simulation
2023-04-26 08:51:38.321 INFO (MainThread) [homeassistant.setup] Setup of domain presence_simulation took 0.0 seconds
2023-04-26 08:51:38.342 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 3.5 seconds
2023-04-26 08:51:38.348 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 3.5 seconds
2023-04-26 08:51:38.350 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/google_fit/sensor.py", line 628, in update
sleep_dataset = self._client.users().sessions().list(userId='me',fields='session',startTime=starttime,endTime=endtime).execute()
AttributeError: 'NoneType' object has no attribute 'users'
2023-04-26 08:51:38.421 INFO (SyncWorker_4) [homeassistant.loader] Loaded google_translate from homeassistant.components.google_translate
2023-04-26 08:51:38.429 INFO (MainThread) [homeassistant.setup] Setting up co2signal
2023-04-26 08:51:38.430 INFO (MainThread) [homeassistant.setup] Setup of domain co2signal took 0.0 seconds
2023-04-26 08:51:38.446 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 2.6 seconds
2023-04-26 08:51:38.449 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/google_fit/sensor.py", line 524, in update
for point in self._get_dataset(self.DATA_SOURCE)["point"]:
File "/config/custom_components/google_fit/sensor.py", line 284, in _get_dataset
return self._client.users().dataSources(). \
AttributeError: 'NoneType' object has no attribute 'users'
2023-04-26 08:51:38.465 INFO (MainThread) [homeassistant.setup] Setting up buienradar
2023-04-26 08:51:38.466 INFO (MainThread) [homeassistant.setup] Setup of domain buienradar took 0.0 seconds
2023-04-26 08:51:38.480 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.energy
2023-04-26 08:51:38.488 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/google_fit/sensor.py", line 557, in update
for point in self._get_dataset(self.DATA_SOURCE)["point"]:
File "/config/custom_components/google_fit/sensor.py", line 284, in _get_dataset
return self._client.users().dataSources(). \
AttributeError: 'NoneType' object has no attribute 'users'
2023-04-26 08:51:38.523 INFO (MainThread) [homeassistant.setup] Setting up camera
2023-04-26 08:51:38.537 INFO (MainThread) [homeassistant.setup] Setup of domain camera took 0.0 seconds
2023-04-26 08:51:38.543 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/google_fit/sensor.py", line 590, in update
for point in self._get_dataset(self.DATA_SOURCE)["point"]:
File "/config/custom_components/google_fit/sensor.py", line 284, in _get_dataset
return self._client.users().dataSources(). \
AttributeError: 'NoneType' object has no attribute 'users'

```

**Comment by jellewie** [comment]
Just going to cross reference things that look the same
#32 
#26

Maybe they can be bundled together?

**Comment by MrAct1on** [comment]
I get the same error
